"""Messages table

Revision ID: 3a19f82418f8
Revises: c6575afabb3c
Create Date: 2025-11-29 22:42:22.255114

"""

from collections.abc import Sequence

import sqlalchemy as sa  # noqa
from alembic import op  # noqa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3a19f82418f8"
down_revision: str | Sequence[str] | None = "c6575afabb3c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message",
        sa.Column("chat_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role", sa.Enum("USER", "AI", name="messagerole"), nullable=False
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True, precision=6),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("system", sa.Text(), nullable=True),
        sa.Column(
            "usage", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chat.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("message")
    # ### end Alembic commands ###
