"""Add model column on Message table

Revision ID: 9af1e68c4409
Revises: 3a19f82418f8
Create Date: 2025-11-30 03:01:53.659145

"""

from collections.abc import Sequence

import sqlalchemy as sa  # noqa
from alembic import op  # noqa

# revision identifiers, used by Alembic.
revision: str = "9af1e68c4409"
down_revision: str | Sequence[str] | None = "3a19f82418f8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.add_column(sa.Column("model", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.drop_column("model")

    # ### end Alembic commands ###
