"""Change Message content model

Revision ID: e3f1dcb1f26d
Revises: 9af1e68c4409
Create Date: 2025-11-30 15:35:59.762549

"""

from collections.abc import Sequence

import sqlalchemy as sa  # noqa
from alembic import op  # noqa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e3f1dcb1f26d"
down_revision: str | Sequence[str] | None = "9af1e68c4409"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.alter_column(
            "content",
            existing_type=sa.TEXT(),
            type_=postgresql.JSONB(astext_type=sa.Text()),
            existing_nullable=False,
            postgresql_using="content::jsonb",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.alter_column(
            "content",
            existing_type=postgresql.JSONB(astext_type=sa.Text()),
            type_=sa.TEXT(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
